name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up environment
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Test
      run: make test
  
  coverage:
    needs: [ test ]
    if: github.event_name == 'push'
    runs-on: ubuntu-20.04
    name: coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Produce Coverage
        run: go test -coverprofile=./coverage.txt ./...
      - name: Upload Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
